FROM continuumio/miniconda3
MAINTAINER Ronald Denaux <rdenaux@expertsystem.com>
COPY docker/timezone /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata
RUN apt-get update && apt-get install -y \
   build-essential \
   lsb-release

# add a user
RUN useradd -ms /bin/bash -u 50990 acred

# config and log folders
RUN mkdir -p /opt/claimneuralindex /etc/claimneuralindex /var/log/claimneuralindex
ENV PATH="/opt/claimneuralindex:${PATH}"
WORKDIR /opt/claimneuralindex

RUN conda update -n base -c defaults conda \
    && conda install -c pytorch faiss-cpu \
    && conda install -c conda-forge uwsgi \
    && conda install -c anaconda pip    

# use pip to install the other claimneuralindex requirements
COPY claimneuralindex/requirements-claimneuralindex.txt ./
COPY requirements-torch.txt ./

RUN pip install -r requirements-torch.txt -f https://download.pytorch.org/whl/torch_stable.html \
 && pip install -r requirements-claimneuralindex.txt

# copy config 
COPY acred.ini /etc/claimneuralindex/

# copy library
COPY claimneuralindex/ ./claimneuralindex/
COPY stance/ ./stance/
COPY esiutils/ ./esiutils/

# copy required resources
# none at the image level,
#  resources are available via attached volume for easy reloading

# copy additional stuff 
COPY ./wsgi/wsgi-claimneuralindex-api.ini ./
COPY ./wsgi/wsgi-claimneuralindex-api.py ./
COPY *.py ./

# correct permissions
RUN chown -R acred /opt/claimneuralindex
RUN chgrp -R acred /opt/claimneuralindex

# expose ports
EXPOSE 8080
EXPOSE 9001

# start a shell?
CMD ["bash"]
